<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find all articles
	 * @return query to use with KnpPaginatorBundle
	 */
	public function findAllQuery(){

		$query = $this->getEntityManager()->getRepository('AppBundle:Article')
		->createQueryBuilder('p')
	    ->orderBy('p.createdAt', 'DESC')
	    ->getQuery();

		return $query;
	}
}
